## Table of Contents

* Important things  about Numpy and Pandas
* Starting with Numpy
* Starting with Pandas


##  Important things about Numpy and Pandas

1. The data manipulation capabilities of pandas are built on top of the numpy library. In a way, numpy is a dependency of the pandas library.

2. Pandas is best at handling tabular data sets comprising different variable types (integer, float, double, etc.). In addition, the pandas library can also be used to perform even the most naive of tasks such as loading data or doing feature engineering on time series data.

3. Numpy is most suitable for performing basic numerical computations such as mean, median, range, etc. Alongside, it also supports the creation of multi-dimensional arrays.

Just to give you a flavor of the numpy library, we'll quickly go through its syntax structures and some important commands such as slicing, indexing, concatenation, etc. All these commands will come in handy when using pandas as well. Let's get started!

## Starting with Numpy

In [ ]:
#load the library and check its version, just to make sure we aren't using an older version
import numpy as np
np.__version__

'1.20.3'

In [ ]:
#create a list comprising numbers from 0 to 20
L = list(range(21))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
#converting integers to string - this style of handling lists is known as list comprehension.
[str(c) for c in L]

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20']

In [ ]:
#List comprehension offers a versatile way to handle list manipulations tasks easily.
[type(item) for item in L]

[int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int]

### Creating Arrays
Numpy arrays are homogeneous in nature, i.e., they comprise one data type (integer, float, double, etc.) unlike lists.

In [ ]:
#creating arrays
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#creating a 3 row x 8 column matrix
np.ones((3,8), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#creating a matrix with a predefined value
np.full((3,5),1.23)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
#create an array with a set sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#create an array of even space between the given range of values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0, 1, (3,3))

array([[-1.54584752,  1.85250222,  0.56524976],
       [-0.16939198, -0.72697093,  0.59454586],
       [-1.35014582,  0.66055621, -1.16407706]])

In [ ]:
#create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#set a random seed
np.random.seed(0)


x1 = np.random.randint(10, size=4) #one dimension
x2 = np.random.randint(10, size=(3,5)) #two dimension
x3 = np.random.randint(10, size=(3,5,5)) #three dimension


print("x1 ndim:", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim: 1
x1 shape: (4,)
x1 size:  4


In [ ]:
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim: 2
x2 shape: (3, 5)
x2 size:  15


In [ ]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim: 3
x3 shape: (3, 5, 5)
x3 size:  75


### Array Indexing
The important thing to remember is that indexing in python starts at zero.

In [ ]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [ ]:
#assess value to index zero
x1[0]

4

In [ ]:
#assess fifth value
x1[4]

8

In [ ]:
#get the last value
x1[-1]

4

In [ ]:
#get the second last value
x1[-2]

8

In [ ]:

#in a multidimensional array, we need to specify row and column index
x2=np.array([[3, 7, 5, 5],[0, 1, 5, 9],[3, 0, 5, 0]])
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [ ]:
#3rd row and last value from the 3rd column
x2[2,-1]

0

In [ ]:
#replace value at 0,0 index
x2[0,0] = 12
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

### Array Slicing
Now, we'll learn to access multiple or a range of elements from an array.

In [ ]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#from start to 4th position
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
#from 4th position to end
x[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
#from 4th to 6th position
x[4:7]

array([4, 5, 6])

In [ ]:
#return elements at even place
x[ : : 2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#return elements from first position step by two
x[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#reverse the array
x[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

### Array Concatenation

Many a time, we are required to combine different arrays. So, instead of typing each of their elements manually, you can use array concatenation to handle such tasks easily.

In [ ]:
#You can concatenate two or more arrays at once.
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [ ]:
#You can also use this function to create 2-dimensional arrays.
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Using its axis parameter, you can define row-wise or column-wise matrix
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

what if you are required to combine a 2D array with 1D array? In such situations, we  can use `np.vstack` or `np.hstack` to do the task. Let's see how!

In [ ]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [ ]:
#Similarly, you can add an array using np.hstack
z = np.array([[9],[9]])
np.hstack([grid,z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

 we can split the arrays based on pre-defined positions. Let's see how!

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x1,x2,x3 = np.split(x,[3,6])
print(x1,x2,x3)

[0 1 2] [3 4 5] [6 7 8 9]


In [ ]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper,lower = np.vsplit(grid,[2])
print (upper, lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In addition, there are several other mathematical functions available in the numpy library such as sum, divide, multiple, abs, power, mod, sin, cos, tan, log, var, min, mean, max, etc. which you can be used to perform basic arithmetic calculations. Feel free to refer to numpy documentation for more information on such functions.

Let's move on to pandas now. Make sure you following each line below because it'll help you in doing data manipulation using pandas.

## Let's start with Pandas

In [ ]:
#load library - pd is just an alias. 
import pandas as pd

In [ ]:
#create a data frame - dictionary is used here where keys get converted to column names and values to row values.
data = pd.DataFrame({'Country': ['India','Nepal','Pakistan','Bangladesh','Bhutan'],
                    'Rank':[11,40,100,130,101]})
data

Country  Rank
0       India    11
1       Nepal    40
2    Pakistan   100
3  Bangladesh   130
4      Bhutan   101

In [ ]:
#We can do a quick analysis of any data set using:
data.describe()

Rank
count    5.000000
mean    76.400000
std     49.084621
min     11.000000
25%     40.000000
50%    100.000000
75%    101.000000
max    130.000000

To get the complete information about the data set, we can use`info()` function.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [ ]:
#Let's create another data frame.
data = pd.DataFrame({'group':['x', 'x', 'x', 'y','y', 'y', 'z', 'z','z'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     x     4.0
1     x     3.0
2     x    12.0
3     y     6.0
4     y     7.5
5     y     8.0
6     z     3.0
7     z     5.0
8     z     6.0

In [ ]:
#Let's sort the data frame by ounces - inplace = True will make changes to the data
data.sort_values(by=['ounces'],ascending=True,inplace=False)

data = data.sort_values(by=['ounces'],ascending=True)

group  ounces
1     x     3.0
6     z     3.0
0     x     4.0
7     z     5.0
3     y     6.0
8     z     6.0
4     y     7.5
5     y     8.0
2     x    12.0

We can sort the data by not just one column but multiple columns as well.

In [ ]:
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

group  ounces
2     x    12.0
0     x     4.0
1     x     3.0
5     y     8.0
4     y     7.5
3     y     6.0
8     z     6.0
7     z     5.0
6     z     3.0

In [ ]:
#create another data with duplicated rows
data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [ ]:
#sort values 
data.sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [ ]:
#remove duplicates - ta da! 
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

we can also remove duplicates based on a particular column. Let's remove duplicate values from the k1 column.

In [ ]:
data.drop_duplicates(subset='k1')

k1  k2
0  one   3
3  two   3

Now, we will learn to categorize rows based on a predefined criteria. It happens a lot while data processing where you need to categorize a variable. 

In [ ]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [ ]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

def meat_2_animal(series):
    if series['food'] == 'bacon':
        return 'pig'
    elif series['food'] == 'pulled pork':
        return 'pig'
    elif series['food'] == 'pastrami':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'honey ham':
        return 'pig'
    else:
        return 'salmon'


#create a new variable
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [ ]:
#another way of doing it is: convert the food values to the lower case and apply the function
lower = lambda x: x.lower()
data['food'] = data['food'].apply(lower)
data['animal2'] = data.apply(meat_2_animal, axis='columns')
data

food  ounces  animal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

Another way to create a new variable is by using the assign function.

In [ ]:
data.assign(new_variable = data['ounces']*14)

food  ounces  animal animal2  new_variable
0        bacon     4.0     pig     pig          56.0
1  pulled pork     3.0     pig     pig          42.0
2        bacon    12.0     pig     pig         168.0
3     pastrami     6.0     cow     cow          84.0
4  corned beef     7.5     cow     cow         105.0
5        bacon     8.0     pig     pig         112.0
6     pastrami     3.0     cow     cow          42.0
7    honey ham     5.0     pig     pig          70.0
8     nova lox     6.0  salmon  salmon          84.0

Let's remove the column animal2 from our data frame.

In [ ]:
data.drop('animal2',axis='columns',inplace=True)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

 A quick method for imputing missing values is by filling the missing value with any random number. Not just missing values, you may find lots of outliers in your data set, which might require replacing. 

In [ ]:
#Series function from pandas are used to create arrays
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [ ]:
#replace -999 with NaN values
data.replace(-999, np.nan,inplace=True)
data

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [ ]:
#We can also replace multiple values at once.
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace([-999,-1000],np.nan,inplace=True)
data

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

Now, let's learn how to rename column names and axis (row names).

In [ ]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [ ]:
#Using rename function
data.rename(index = {'Ohio':'SanF'}, columns={'one':'one_p','two':'two_p'},inplace=True)
data

one_p  two_p  three  four
SanF          0      1      2     3
Colorado      4      5      6     7
New York      8      9     10    11

In [ ]:
#You can also use string functions
data.rename(index = str.upper, columns=str.title,inplace=True)
data

One_P  Two_P  Three  Four
SANF          0      1      2     3
COLORADO      4      5      6     7
NEW YORK      8      9     10    11

Learn to categorize (bin) continuous variables.

In [ ]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

We'll divide the ages into bins such as 18-25, 26-35,36-60 and 60 and above.

In [ ]:
#Understand the output - '(' means the value is included in the bin, '[' means the value is excluded
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [ ]:
#To include the right bin value, we can do:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [ ]:
#Let's check how many observations fall under each bin
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

Pass a unique name to each label.

In [ ]:
bin_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']
new_cats = pd.cut(ages, bins,labels=bin_names)

pd.value_counts(new_cats)

Youth         5
YoungAdult    3
MiddleAge     3
Senior        1
dtype: int64

In [ ]:
#we can also calculate their cumulative sum
pd.value_counts(new_cats).cumsum()

Youth          5
YoungAdult     8
MiddleAge     11
Senior        12
dtype: int64

Let's learn about grouping data and creating pivots in pandas. It's an immensely important data analysis method which you'd probably have to use on every data set you work with.

In [ ]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  1.509445 -0.038224
1    a  two  1.067775  0.367974
2    b  one -0.686589 -0.044724
3    b  two  0.014873 -0.302375
4    a  one -0.375666 -2.224404

In [ ]:
#calculate the mean of data1 column by key1
grouped = df['data1'].groupby(df['key1'])
grouped.mean()

key1
a    0.733851
b   -0.335858
Name: data1, dtype: float64

let's see how to slice the data frame.

In [ ]:
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-03 -0.491150  0.712678  1.113340 -2.153675
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057
2013-01-05 -1.050758  1.012079  1.543716 -0.402115
2013-01-06  0.864749 -0.226869  0.811160  0.287795

In [ ]:
#get first n rows from the data frame
df[:3]

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-03 -0.491150  0.712678  1.113340 -2.153675

In [ ]:
#slice based on date range
df['20130101':'20130104']

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-03 -0.491150  0.712678  1.113340 -2.153675
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057

In [ ]:
#slicing based on column names
df.loc[:,['A','B']]

A         B
2013-01-01  0.724006  0.359003
2013-01-02  0.852926  0.018357
2013-01-03 -0.491150  0.712678
2013-01-04 -0.416111 -1.070897
2013-01-05 -1.050758  1.012079
2013-01-06  0.864749 -0.226869

In [ ]:
#slicing based on both row index labels and column names
df.loc['20130102':'20130103',['A','B']]

A         B
2013-01-02  0.852926  0.018357
2013-01-03 -0.491150  0.712678

In [ ]:
#slicing based on index of columns
df.iloc[3] #returns 4th row (index is 3rd)

A   -0.416111
B   -1.070897
C    0.221139
D   -1.123057
Name: 2013-01-04 00:00:00, dtype: float64

In [ ]:
#returns a specific range of rows
df.iloc[2:4, 0:2]

A         B
2013-01-03 -0.491150  0.712678
2013-01-04 -0.416111 -1.070897

In [ ]:
#returns specific rows and columns using lists containing columns or row indexes
df.iloc[[1,5],[0,2]] 

A         C
2013-01-02  0.852926  0.428304
2013-01-06  0.864749  0.811160

Similarly, we can do Boolean indexing based on column values as well. This helps in filtering a data set based on a pre-defined condition.

In [ ]:
df[df.A > 0.5]

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-06  0.864749 -0.226869  0.811160  0.287795

In [ ]:
#we can copy the data set
df2 = df.copy()
df2['E']=['one', 'one','two','three','four','three']
df2

A         B         C         D      E
2013-01-01  0.724006  0.359003  1.076121  0.192141    one
2013-01-02  0.852926  0.018357  0.428304  0.996278    one
2013-01-03 -0.491150  0.712678  1.113340 -2.153675    two
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057  three
2013-01-05 -1.050758  1.012079  1.543716 -0.402115   four
2013-01-06  0.864749 -0.226869  0.811160  0.287795  three

In [ ]:
#select rows based on column values
df2[df2['E'].isin(['two','four'])]

A         B         C         D     E
2013-01-03 -0.491150  0.712678  1.113340 -2.153675   two
2013-01-05 -1.050758  1.012079  1.543716 -0.402115  four

In [ ]:
#select all rows except those with two and four
df2[~df2['E'].isin(['two','four'])]

A         B         C         D      E
2013-01-01  0.724006  0.359003  1.076121  0.192141    one
2013-01-02  0.852926  0.018357  0.428304  0.996278    one
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057  three
2013-01-06  0.864749 -0.226869  0.811160  0.287795  three

We can also use a query method to select columns based on a criterion.

In [ ]:
#list all columns where A is greater than C
df.query('A > C')

A         B         C         D
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-06  0.864749 -0.226869  0.811160  0.287795

In [ ]:
#using OR condition
df.query('A < B | C > A')

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-03 -0.491150  0.712678  1.113340 -2.153675
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057
2013-01-05 -1.050758  1.012079  1.543716 -0.402115

Pivot tables are extremely useful in analyzing data using a customized tabular format.

In [ ]:
#create a data frame
data = pd.DataFrame({'group': ['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [ ]:
#calculate means of each group
data.pivot_table(values='ounces',index='group',aggfunc=np.mean)

ounces
group          
a      6.333333
b      7.166667
c      4.666667

In [ ]:
#calculate count by each group
data.pivot_table(values='ounces',index='group',aggfunc='count')

ounces
group        
a           3
b           3
c           3

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('filename.csv')
df.head
df.tail
shape
info
describe